services:
  postgres_db:
    image: postgres:16.8
    container_name: postgres
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: CjZwTK1f03pY
      POSTGRES_DB: CryptoBank
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgresql", "d", "CryptoBank"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    container_name: BECryptoBank
    image: becryptobank-app:latest
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_NAME: CryptoBank
      DB_USER: postgresql
      DB_PASS: CjZwTK1f03pY
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data: