spring:
  application:
    name: BE-Crypto-Bank
  datasource:
    url: jdbc:postgresql://14.225.206.68:5432/CryptoBank
    username: postgres
    password: 74ZLdPPJab8zNRHh
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect